### ISSUE TITLE
add experiment template

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_PTB#1]

**Comment by marcobarilari** [comment]
Hi there, I'll take care of this.

**Comment by Remi-Gau** [comment]
I realized you will have to create a `setParameters.m` template function. 

But I guess you knew that. :wink:

**Comment by marcobarilari** [comment]
Thinking about how to make it the easiest to get, I think we might need 2 things:

(1) a canvas, scripts showing the very basic info needed to run an experiment powered by CPP_BIDS and CPP_PTB

(2) a demo, an actual experiment (e.g. press a button every time you perceive a sound a flash together, this is really the first thing that came to my mind) that is runnable and shows how actually build an experiment shot specific needs

LMK

**Comment by Remi-Gau** [comment]
Yeah I have not taken the time to put tons of time into this but both of those points make sense. :-)

**Comment by Remi-Gau** [comment]
As discussed on slack it might be even easier to create a template repository we can easily reuse when coding a new experiment that has an experiment template in it with all the submodules, continuous integration for checking code quality and unit tests...

**Comment by marcobarilari** [comment]
Move to PTB experiment template

**Comment by Remi-Gau** [comment]
closing this now.

let's move the discussion to the PTB template repo
