### ISSUE TITLE
using waitForTrigger as a timestamp

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#123]
_from #116_

> @CerenB 
> Hello @marcobarilari, I know you close this issue/merged this PR. But I want to ask two things.
> 
> I'm using this function to get timestamp for my onsets by setting this line:
> [sec, keyCode] = KbPressWait(deviceNumber);
> and have the sec as output of this function.
> sec = waitForTrigger(varargin)
> Then I call in my main exp script:
> cfg.experimentStart = waitForTrigger(cfg)
> Question here is do you see any logic mistake for storing onsets with this way of using the function?
> 
> When I update my submodule with this PR, how can I "cherry pick" ? :D @Remi-Gau

---

> @marcobarilari 
> Hello!
> 
> (1) I don't think that there is any "logic mistake" in using such secondary measures unless they are not in the right place in a script. (primary one would be like startTime = PsychPortAudio(‘Start’, ...). It depends what is your purpose.
> 
> Though, I understand now why updating the submodels breaks your scripts :) and maybe here is the annoying thing that might tell you to not change function this way.
> 
> If I can suggest, you have the original waitForTrigger that, if I understand correctly, will pace your stimulation and right after that you can use
> 
>     
>      waitForTrigger(cfg)
> 
>     onset = GetSecs;
> 
>     *stimulation*
> 
>     estStopTime = GetSecs;
> 
>     duration = estStopTime - onset;

--- 

> @CerenB CerenB 12 hours ago Member
> Though, I understand now why updating the submodels breaks your scripts :) and maybe here is the annoying thing that might tell you to not change function this way.
> 
> look who is being mean now.. I only changed this function - only today. all the other submodule issues are due to submodule itself 👯
> 
> I'm using like this and it makes puurfect onsets (e.g. it's precisely right after my onsetDelay the stim starts) - without annoying decimal .00345 sort of things:
> 
>     % wait for trigger from fMRI
>     cfg.experimentStart = waitForTrigger(cfg);
>     ...
>     % wait for baseline delays and then start the audio
>     onset = PsychPortAudio('Start', cfg.audio.pahandle, [], ...
>         cfg.experimentStart + cfg.timing.onsetDelay,1);
> See my point? if I use GetSecs, then everything will be slightly weirdly numbered...
> 
> Also @marcobarilari I see that you do not use any buffer for your audio exp, so no audio cracks? That's good but I wonder you are buffering somewhere in your audio-mot localiser?
> 

---

> @marcobarilari marcobarilari 11 hours ago Author Member
> I'm using like this and it makes puurfect onsets
> 
> it is actually a fair point.....
> 
> I see that you do not use any buffer for your audio exp
> 
> we fill the buffer here
> 
> subfun/doAuditoryMotion.m line 46
> 
> % Start the sound presentation
> PsychPortAudio('FillBuffer', cfg.audio.pahandle, sound);
> PsychPortAudio('Start', cfg.audio.pahandle);
> onset = GetSecs;

---

> @CerenB CerenB 11 hours ago Member
> yup i saw that one and i was using that as well FillBuffer and Start... then in every first run, in the very first block there were audio cracks, so I'm using Start with option (see below). Then I remembered during my aud-mot exp, i was also inserting such option:
> 
> PsychPortAudio('Start', cfg.audio.pahandle, [], ...
>         cfg.experimentStart + cfg.timing.onsetDelay,1)
> Just to warn you to pay attention to audio ｡◕‿◕｡
> 
> btw, if you see my point,...does it mean you would consider changing the waitForTrigger for such optional use? ♥‿♥
> 

---

> @marcobarilari
> marcobarilari 10 seconds ago Author Member
> Big dilemma :) can we pause this discussion for a couple of days? Maybe let me move this conversation in an issue and let's come back to it later.

**Comment by marcobarilari** [comment]
back here. Could you explain better what's the gain of using:

```matlab
cfg.experimentStart = waitForTrigger(cfg);

```

instead of

```matlab
waitForTrigger(cfg);

% Stores the onset time in cfg.experimentStart, from CPP_PTB
cfg = getExperimentStart(cfg); 
```
You said: 

> See my point? if I use GetSecs, then everything will be slightly weirdly numbered...

do you have an example?

**Comment by CerenB** [comment]
welcome back! 
First thing first, not everyone is using getExperimentStart and also not everyone would like to have visual stimulation. More seriously, the vbl flip or Screen flip depends on how good your laptop/stimulation PC. We already know that macbook is not good. And even with a nice, new laptop I'm experiencing delays with flipping the screen. 
So what happens when I take the timestamp from vbl is this:
onset:
5.64041
23.88041
42.12041
60.36041

If I take the timestamp from trigger - which is also the actual time point of fMRI goes on, and also when I use the PTB function with the timestamp:

cfg.experimentStart = waitForTrigger(cfg);
...
onset = PsychPortAudio('Start', cfg.audio.pahandle, [], ...
    cfg.experimentStart + cfg.timing.onsetDelay,1);

onsets:
5.302000
23.542000
41.782000
60.022000

Please let me know what you think. I might be missing something.

**Comment by Remi-Gau** [comment]
hey @CerenB 

> First thing first, not everyone is using getExperimentStart and also not everyone would like to have visual stimulation. 

That's a good point. Sort of point to the fact that our getExperimentStart should also cover the use case of experiment with no visual stimuli or least for those where the experiment start is more tied to something else.

For this: `cfg.experimentStart = waitForTrigger(cfg)`

Not sure how you implemented it but we could simply have `KbCheck` return an actual time stamp here that we use as an output argument to the function.

```
function lastTriggerTimeStamp = waitForTrigger(varargin)
```

```
        while triggerCounter < nbTriggersToWait

            keyCode = []; %#ok<NASGU>

            [~, lastTriggerTimeStamp, keyCode] = KbCheck(deviceNumber);
```

https://github.com/cpp-lln-lab/CPP_PTB/blob/cfa1f86bb3bf3c7dd87cdc570a97cc75b4f090a7/src/waitForTrigger.m#L46

Is that what you did? Would that work for you?
