### ISSUE TITLE
Make sure that debug mode takes care of killing the eyetracker

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#161]
You think / need this code to do **Add `cfg.eyeTracker.do = false;` as default when run in debug mode**.

I think this just need to add in `setDefaultsPTB` something like 

if cfg.debug.do

```
if isfield(cfg, 'debug') && cfg.debug.do

    cfg.eyeTracker.do = false

end
```

**Comment by Remi-Gau** [comment]
go for it
