### ISSUE TITLE
[BUG]:  unfold does not print a new line at the end of the struc

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

```
cfg.timing.onsetDelay =	0.000000;
cfg.timing.triggerIBI =	4.000000;
cfg.verbose =	1.000000;
>> 
```

### Current Behavior

```
cfg.timing.onsetDelay =	0.000000;
cfg.timing.triggerIBI =	4.000000;
cfg.verbose =	1.000000;>> 
```

### Error message

No error message, just esthetics

### Environment

```markdown
- OS:
- Matlab:
- SPM:
```

### Anything else?

Writing this here but it is valid for any repo with unfold that btw it is amazing :)

**Comment by Remi-Gau** [comment]
Yup I tried to fix this but because the function is recursive it ended also skipping a million lines in the middle of the output.
Dirty hack in CPP SPM was creating a new function called unfoldStruct that calls unfold and adds a line after.

**Comment by marcobarilari** [comment]
yep, likewise. I tried but it was skipping lines

**Comment by Remi-Gau** [comment]
Actually need to check but it should be doable to check the status of the call stack and only print an extra line if the unfold is the last function on the stack...
Not sure if I am talking English here...

**Comment by marcobarilari** [comment]
No, it is clear, this is a devil function that calls itself

**Comment by Remi-Gau** [comment]
I think I fixed it with this at the end of the function:

```matlab
  callStack = dbstack();
  if numel(callStack) > 1 && ~strcmp(callStack(2).name, mfilename())
    fprintf('\n');
  elseif numel(callStack) == 1 && strcmp(callStack(1).name, mfilename())
    fprintf('\n');
  end
```
