### ISSUE TITLE
Easier alternative to `mpm` to manage this repo inside other projects

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#21]
A not exhaustive list of alternatives (literally everything is coming up to my mind), please provide any comment and solutions. I would be also happy to suggest all of them in the read-me with user-case examples.

-  **[MatlabPackageManager](https://github.com/mobeets/mpm)**
_pros_: 'easy' to get and then forget about it, 
_cons_: does it work in octave? Would be better to download a specific version/commit, it can only be used with one specific version of the package (right?)

- **Submodules**
_pros_: in principle, downloading the experiment you have the whole package plus the benefit to stay updated and use version control of this dependency. Can probably handle a use case in which one uses different version on different projects (e.g. older and newer projects).
_cons_: for pro users and not super clear how to use it at the moment.

- **Download a specific version and c/p it in a `subfun` folder**
_pros_: the easiest solution to share the code and 'installing' it on the stimulation computer (usually not the one used to develop the code).
_cons_: extreme solution useful only at the very latest stage (i.e. one minute before acquiring your data); prone to be customized/modified  (is it what we want?)

**Comment by Remi-Gau** [comment]
I would say that option 1 is out until it becomes easier to use and octave compatible.

I would make option 2 the default.

Option 3 has the advantage that it is not mutually exclusive with option 2 and can be used to over ride it.

**Comment by CerenB** [comment]
The 3rd option is not under version control, right? 
What I did for my current exp, I have CPP repos (BIDS and PTB) in separate folders. But I've inserted the "copy" of these repos inside my exp scripts. Every time there's a major update on CPP repos, I copy paste manually into my exp script folder. 
Is 3rd option like the one I explained above?

**Comment by Remi-Gau** [comment]
From my understanding, yes the 3rd option describes what you have been doing. :-)



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by Remi-Gau** [comment]
OK so I played around with submodules this morning on a dummy example and I did this.

Have a look and let me know if this makes sense and works for you.

https://github.com/Remi-Gau/repo_with_submod

**Comment by Remi-Gau** [comment]
@marcobarilari @CerenB 

I added some sections to the READMEs.

Let me know what you think.

https://github.com/cpp-lln-lab/CPP_PTB#how-to-install
https://github.com/cpp-lln-lab/CPP_BIDS#how-to-install

**Comment by CerenB** [comment]
I'm new to submodules, sorry for my naive question below. 

PTB//BIDS also have their own submodules to get, right? (I think BIDS repo has submodules) In order to get those when I install the BIDS repo, I'll also do the following in the README file? Or that would be with:
Option1 : 
`git submodule foreach --recursive 'git submodule init'
`

Option2:
_Add it as a submodule in the repo you are working on._

```
cd fullpath_to_directory_where_to_install
# use git to download the code
git submodule add https://github.com/cpp-lln-lab/CPP_PTB.git
# move into the folder you have just created
cd CPP_PTB
# add the src folder to the matlab path and save the path
matlab -nojvm -nosplash -r "addpath(fullfile(pwd))"
```
_To get the latest commit you then need to update the submodule with the information on its remote repository and then merge those locally.

git submodule update --remote --merge_

**Comment by CerenB** [comment]
Another question is with this `submodule` installing as you explained in `README`, is good for using `CPP_PTB` as a submodule within my experiment folder. I'm preparing my scripts in one repo and I'll add `PTB` repo within this as a `submodule`. Right? 
Then somewhere it should "save" the version so I can keep track of it?

**Comment by Remi-Gau** [comment]
Yeah I am figuring out submodule as I go too.

So say you want to clone a repo that has some nested submodules, then you would type this to get the content of all the submodules at once (here with my retinotopy repo):

```
git clone --recurse-submodules https://github.com/Remi-Gau/retinotopy_experiment_fMRI.git
```

And apparently this would be the way to do it "by hand"

```bash
# clone the repo
git clone https://github.com/Remi-Gau/retinotopy_experiment_fMRI.git

# go into the directory
cd retinotopy_experiment_fMRI

# initialize and get the content of the first level of submodules  (CPP_PTB and CPP_BIDS)
git submodule init
git submodule update 

# get the nested submodules JSONio and BIDS-matlab for CPP_BIDS
git submodule foreach --recursive 'git submodule init'
git submodule foreach --recursive 'git submodule update'
```

Does that help?

**Comment by Remi-Gau** [comment]
> Then somewhere it should "save" the version so I can keep track of it?

Actually this part is simpler than I thought as a submodule is directly "linked" to a specific commit in the history of the repo.

For example, in CPP_BIDS the submodule have an `@somethingSomethingSomething`. This `somethingSomethingSomething` is the "shasum" of the commit (its codename) it is "tracking".

https://github.com/cpp-lln-lab/CPP_BIDS/tree/master/lib

So that is effectively tracking which version of the dependency you are using.

Does that make sense?

**Comment by CerenB** [comment]
Yes that's clear now, thank you! 
Shall we add your first example into README file? I like your example, if you dont like to insert it into README, I'll simply keep it in some notes of mine :)

**Comment by Remi-Gau** [comment]
Sure I think it belongs in the readme.

Wanna add it?

**Comment by CerenB** [comment]
created the PR #59

**Comment by Remi-Gau** [comment]
Let me know if I can close this or if we need to add more info.

**Comment by marcobarilari** [comment]
I think we can close this one

**Comment by Remi-Gau** [comment]
okidoki
