### ISSUE TITLE
Sandbox stand-alone function to develop ptb stimulation code

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#24]
Hey geeks,

as you know I am working on the stimulation part of our experiment developing a grating motion. This is really preliminary stage and a lot of trial and error. 

Developing it inside the experiment (with multiple levels of complexity e.g. CPP_PTB functions, design etc) it is just frustrating and time-consuming (starting the experiment requires a bit).

A solution I found helpful is to have a stand-alone function with a fixed part (e.g. to init PTB) and a playground part to develop your stimulation. The purpose is very simple: just develop your stimulation in a sandbox script, when ready add the needed vars on your `setParameters.m` function and the code for the stimulation in a separate function.

To have a look, see the annexed PR #23 . It comes with a cooked example from [Peter Scarfe.](http://peterscarfe.com/contrastgratingdemo.html). Do you think it could be of interest to this repo?

Of course, it is not commented either pretty or in line with our code style plus at the moment it is built to serve my purpose (not ready to developed auditory stimulation). Might need to hear from you if it is worth adding it here and spend time on it. 

Open to any idea and to be dropped cause it might be not of general interest.

**Comment by Remi-Gau** [comment]
Good idea.

Just wondering about how much overlap there is with the idea of creating a "template script" to help us "prototype" our experiment. 

See issue #1

**Comment by marcobarilari** [comment]
I would say that the overlapping is minimum since the template in #1 is basically the experiment *without* the stimulation part (there will be a very basic one as an example), while this stand-alone is only a playground to develop the stimulation. 

So I would say that they are complementary in the whole experiment developing process.

**Comment by Remi-Gau** [comment]
ha. I see.

YES !! This makes total sense.

Will review when I am not "off duty".

**Comment by marcobarilari** [comment]
Sure! This will actually give me more time to make it prettier.
