### ISSUE TITLE
Do we want to run testKeyboards(cfg) at every initPTB?

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_PTB#35]
Might be over aggressive to test this at every PTB init maybe make it dependent on a debug "flag"?

in the subfunction `initKeyboard(cfg)` of `initPTB`

**Comment by CerenB** [comment]
yis!

**Comment by Remi-Gau** [comment]
Yes but paranoid me likes to run a quick test on the response box at the beginning of every run, hence why I am tempted to do this: as it only asks for one button press from the subject this is not huge.

But I realize not everyone likes this so I might just make this run in debug mode as you suggest and call for a keyboard test when I run my experiments only (from the main script and not initPTB) and not bother everyone.

**Comment by CerenB** [comment]
Nice to interact with other experimenters to hear their worries. Ok, I might check it every run as well.
For others, when it's for decoding exp for instance, runs are super short and many, experimenter may not want to lose time with this on every run.

**Comment by Remi-Gau** [comment]
yeah that's what I thought. Your subject might be in the zone and you don't want to disturb them. :-)

**Comment by Remi-Gau** [comment]
Closing this as this was taken care by the previous PR
