### ISSUE TITLE
make fixation cross function more flexible

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_PTB#46]
- [x] decide where the cross will go
- [x] fixation cross or fixation dot

**Comment by marcobarilari** [comment]
Maybe, or not, this is also a good place to discuss what is the best fixation target and if we want to explore more options. 

See this [What is the best fixation target? The effect of target shape on stability of fixational eye movements](https://www.sciencedirect.com/science/article/pii/S0042698912003380?via%3Dihub)

in a nutshell, a black full circle with a white cross with a black point in the center seems to be the best one 

they provide also old code in ptb, should be easy to update it

<img width="61" alt="Screen Shot 2020-07-27 at 18 28 06" src="https://user-images.githubusercontent.com/38101692/88567167-671db400-d037-11ea-9e9b-bf272eac204a.png">

**Comment by Remi-Gau** [comment]
Wow. Some people are really stuying things in details. That's nuts. OK maybe we could make that the default and have a simple dot and cross as alternatives.

**Comment by marcobarilari** [comment]
maybe better the cross as default as it is in the 'experiments nature' (i.e. common use)?
