### ISSUE TITLE
getResponseDemo error

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_PTB#8]
```
During the next 5 seconds we will collect responses on the following keys: 

ALL KEYS


Error using ListenChar (line 108)
Invalid listenFlag provided!  See "help ListenChar" for more information

Error in getResponse (line 69)
        ListenChar(-1);

Error in CPP_getResponseDemo (line 73)
getResponse('init', cfg, expParameters, 1);

```

**Comment by Remi-Gau** [comment]
Huh. That's strange.

If you try to run the following do you get an error too?

```
ListenChar(-1); ListenChar(0);
```

From the the top of my head I am thinking this could be a PTB version issue.

Try `PsychtoolboxVersion`

I am running 3.0.16. What do you have?

**Comment by CerenB** [comment]
yup, it's a version issue! 
I have 3.0.12 

`ListenChar(-1); ListenChar(0);
Error using ListenChar (line 108)
Invalid listenFlag provided!  See "help ListenChar" for more information`

**Comment by Remi-Gau** [comment]
Ah but it is really good to know! 

This way we can add some "requirements" to the repo. I had planned to create "check_version" function: now I know what to put into it. :+1: 

Thanks for checking this and this way helping science and making this world a little less horrible and contributing to world peace. :laughing:

**Comment by CerenB** [comment]
I'm glad to be at the service of science and world piece!
