### ISSUE TITLE
EyeTracker: improve tags in the output

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#84]
from Remi #74 

> Some things need to be added in the main scripts as.
> 
> Like in the visual localizers calls to:
> 
> Eyelink('Message', 'block_start');
> Eyelink('Message', 'trial_start');
> Eyelink('Message', 'block_end');
> 
> Having those in the output of the eyetracker will definitely help us parse the huge tsv we will get.

**Comment by marcobarilari** [comment]
actually we have already an issue on the topic of cpp-lln-lab/localizer_visual_motion#49

**Comment by Remi-Gau** [comment]
@marcobarilari This one can be closed, no?

**Comment by marcobarilari** [comment]
yes!
