### ISSUE TITLE
Screen SkipSyncTest option set 

### ISSUE THREAD

**Issue by CerenB** [cpp-lln-lab/CPP_PTB#90]
Would you consider to make your `initPTB `more flexible with :
`    Screen('Preference', 'SkipSyncTests', 1); `
instead of what you have:
`    Screen('Preference', 'SkipSyncTests', 0); `
With 0 option, most of the macbook pro users will not be able to run their experiment because PTB sync fails and it stops the execution of the whole script.

**Comment by Remi-Gau** [comment]
implementing this now since I am tweaking some minor things on this repo. :-)
