### ISSUE TITLE
create function to initialize RNG seed - must work both for matlab (including "old" versions) AND octave

### ISSUE THREAD

**Issue by Remi-Gau** [cpp-lln-lab/CPP_PTB#95]
I had this function somewhere else but I think this is not ideal

```matlab
function [] = setUpRand()
    % Set up the randomizers for uniform and normal distributions.
    % It is of great importance to do this before anything else!
    rand('state', sum(100, clock));
    randn('state', sum(100, clock));
end
```

@marcobarilari I think this is much more your area of expertise than mine. Can I assign you to this?

Having one function we can reuse across all projects would be super useful.

And also we actually need it for our localizers I think.

**Comment by marcobarilari** [comment]
you mean that I am too way random?? 

I know this one but I do not remember whether it may have some problem with octave, I'll check

`RandStream.setGlobalStream(RandStream('mt19937ar','seed',sum(100*clock)));`

**Comment by Remi-Gau** [comment]
> you mean that I am too way random??

That's exactly what I mean ! :rofl: 

> I know this one but I do not remember whether it may have some problem with octave, I'll check
> 
> `RandStream.setGlobalStream(RandStream('mt19937ar','seed',sum(100*clock)));`

ok cool let me know what you find.
