### ISSUE TITLE
Improve `Add as a submodule` section

### ISSUE THREAD

**Issue by marcobarilari** [cpp-lln-lab/CPP_PTB#96]
from #92 

> ### Example for submodule usage
> 
> So say you want to clone a repo that has some nested submodules, then you would type this to get the content of all the submodules at once (here with my experiment repo):
> ``` bash
> git clone --recurse-submodules https://github.com/user_name/yourExperiment.git
> ```
> This would be the way to do it "by hand"
> 
> ```bash
> # clone the repo
> git clone https://github.com/user_name/yourExperiment.git
> 
> # go into the directory
> cd yourExperiment
> 
> # initialize and get the content of the first level of submodules  (CPP_PTB and CPP_BIDS)
> git submodule init
> git submodule update
> 
> # get the nested submodules JSONio and BIDS-matlab for CPP_BIDS
> git submodule foreach --recursive 'git submodule init'
> git submodule foreach --recursive 'git submodule update'
> ```

@marcobarilari
marcobarilari 8 days ago Member
in 3.2.1 you are describing how to clone a repo with the submodules and not how to use the submodules (and why?) in the repo of a new experiment (e.g. experiment/lib/submodule1 and add the folder to the path in the exp script)

As it is here might be a bit confusing. This example might be more helpful in the repo of an experiment with submodules (e.g. the localizers) to explain how to clone them

**Comment by CerenB** [comment]
I do not know where is 3.2.1 but it might be me who did that example. It was the time I was trying to understand submodule etc.. Feel free to delete/change it.

**Comment by Remi-Gau** [comment]
I think that generally the install section can be improved so I would keep that issue opened as a reminder.

Also I remove the numbering of the TOC in one of my last commits: would you prefer to have it back ?

**Comment by Remi-Gau** [comment]
- [ ] mention that the best way to use it is actually to clone the template_PTB repo : https://github.com/cpp-lln-lab/PTB_experiment

**Comment by Remi-Gau** [comment]
Maybe those having a common install section in the .github repo of the orga might make more sense (since this is a common thing to CPP_BIDS, CPP_PTB and CPP_SPM), we would have only one doc to curate

**Comment by Remi-Gau** [comment]
this is included on the doc on RTD
